ktor:
  development: true
  deployment:
    port: 8080
    watch: [ classes, resources ]
  application:
    modules:
      - com.example.ApplicationKt.module


jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "ktor sample app"
  secret: "secret"


database:
  url: $DB_URL
  user: $DB_USER
  password: $DB_PASSWORD